spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/matcha

server:
  port: 8000

matcha:
  # CORS should only be enabled by default with the "dev" profile
  cors:
    allowed-origins: 'http://localhost:3000'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    allow-credentials: true
    max-age: 1800

  abac:
    cerbos:
      server:
        url: 'localhost:3593'

  file:
    storage:
      local-path: ${user.home}/matcha/storage